name: nim-lang-nightly
summary: Nim programming language, compiler, and other tools.
description: |
  Nim is a compiled, garbage-collected systems programming language with 
  a design that focuses on efficiency, expressiveness, and elegance.
version: 'nightly'
base: core18
grade: devel
confinement: classic

apps:
  nim:
    command: bin/nim
    completer: nim.sh
  nimble:
    command: bin/nimble
    completer: nimble.sh
  nimcsources:
    command: bin/nim_csources
  nimfind:
    command: bin/nimfind
  nimgdb:
    command: bin/nim-gdb
  nimgrep:
    command: bin/nimgrep
  nimpretty:
    command: bin/nimpretty
  nimsuggest:
    command: bin/nimsuggest
  testament:
    command: bin/testament

parts:
  nim-build:
    plugin: dump
    source: https://github.com/nim-lang/Nim.git
    override-build: |
      
      case "$SNAPCRAFT_ARCH_TRIPLET" in
      "x86_64-linux-gnu")
        arch="amd64"
        ;;
      "arm-linux-gnueabihf")
        arch="armhf"
        ;;
      "aarch64-linux-gnu")
        arch="arm64"
        ;;
      "i386-linux-gnu")
        arch="i386"
        ;;
      *)
        echo "Unsupported architecture $SNAPCRAFT_ARCH_TRIPLET"
        exit 1
        ;;
      esac
      
      #build nim
      sh build_all.sh --os linux --cpu $arch

      #cleanup misc files and set permissions
      rm bin/empty.txt
      chmod u+x bin/*

      #prepare and copy binaries to snap
      mkdir "$SNAPCRAFT_PART_INSTALL"/bin
      cp -v bin/* "$SNAPCRAFT_PART_INSTALL"/bin
      
      #prepare and copy libraries to snap
      mkdir "$SNAPCRAFT_PART_INSTALL"/lib
      cp -r lib/* "$SNAPCRAFT_PART_INSTALL"/lib

      #copy bash completion scripts into place
      cp -v tools/nim.bash-completion "$SNAPCRAFT_PRIME"/nim.sh
      cp -v dist/nimble/nimble.bash-completion "$SNAPCRAFT_PRIME"/nimble.sh
    build-packages:
      - gcc
      - git
