name: nim-lang-nightly
summary: Nim programming language, compiler, and other tools.
description: |
  Nim is a compiled, garbage-collected systems programming language with 
  a design that focuses on efficiency, expressiveness, and elegance.
version: 'nightly'
base: core18
grade: devel
confinement: strict

apps:
  nim:
    command: bin/nim
    completer: nim.bash-completion
    plugs: [home]
  nimble:
    command: bin/nimble
    completer: nimble.bash-completion
    plugs: [home, network]
  nimcsources:
    command: bin/nim_csources
    plugs: [home]
  nimfind:
    command: bin/nimfind
    plugs: [home]
  nimgdb:
    command: bin/nim-gdb
    plugs: [home]
  nimgrep:
    command: bin/nimgrep
    plugs: [home]
  nimpretty:
    command: bin/nimpretty
    plugs: [home]
  nimsuggest:
    command: bin/nimsuggest
    plugs: [home]
  testament:
    command: bin/testament
    plugs: [home]
  gcc:
    command: usr/bin/gcc
    plugs: [home]
  clang:
    command: usr/bin/clang
    plugs: [home]

parts:
  nim-build:
    plugin: dump
    source: https://github.com/nim-lang/Nim.git
    override-build: |
      
      case "$SNAPCRAFT_ARCH_TRIPLET" in
      "x86_64-linux-gnu")
        arch="amd64"
        ;;
      "arm-linux-gnueabihf")
        arch="armhf"
        ;;
      "aarch64-linux-gnu")
        arch="arm64"
        ;;
      "i386-linux-gnu")
        arch="i386"
        ;;
      *)
        echo "Unsupported architecture $SNAPCRAFT_ARCH_TRIPLET"
        exit 1
        ;;
      esac
      
      sh build_all.sh --os linux --cpu $arch
      ./koch docs
      rm bin/empty.txt
      chmod u+x bin/*
      mkdir "$SNAPCRAFT_PART_INSTALL"/bin
      mkdir "$SNAPCRAFT_PART_INSTALL"/lib
      mkdir "$SNAPCRAFT_PART_INSTALL"/doc
      mkdir -p "$SNAPCRAFT_PART_INSTALL"/usr/bin
      mkdir "$SNAPCRAFT_PART_INSTALL"/usr/lib
      mv bin/* "$SNAPCRAFT_PART_INSTALL"/bin
      mv lib/* "$SNAPCRAFT_PART_INSTALL"/lib
      mv doc/* "$SNAPCRAFT_PART_INSTALL"/doc
      mv tools/nim.bash-completion "$SNAPCRAFT_PART_INSTALL"
      mv dist/nimble/nimble.bash-completion "$SNAPCRAFT_PART_INSTALL"
      cp /usr/bin/gcc "$SNAPCRAFT_PART_INSTALL"/usr/bin
      cp /usr/bin/clang "$SNAPCRAFT_PART_INSTALL"/usr/bin
      cp -a /usr/lib/clang "$SNAPCRAFT_PART_INSTALL"/usr/lib
      cp -a /usr/lib/llvm-6.0 "$SNAPCRAFT_PART_INSTALL"/usr/lib
      cp -a /usr/lib/gcc "$SNAPCRAFT_PART_INSTALL"/usr/lib
    build-packages:
      - gcc
      - git
      - clang
      - llvm-6.0-dev
      - libc6-dev
