name: nim-lang-nightly
summary: Nim programming language, compiler, and other tools.
description: |
  Nim is a compiled, garbage-collected systems programming language with 
  a design that focuses on efficiency, expressiveness, and elegance.
version: 'nightly'
base: core18
grade: devel
confinement: classic

apps:
  nim:
    command: bin/nim
    plugs: [home]
    completer: nim.sh
  nimble:
    command: bin/nimble
    plugs: [home, network]
    completer: nimble.sh
  nimcsources:
    command: bin/nim_csources
    plugs: [home]
  nimfind:
    command: bin/nimfind
    plugs: [home]
  nimgdb:
    command: bin/nim-gdb
    plugs: [home]
  nimgrep:
    command: bin/nimgrep
    plugs: [home]
  nimpretty:
    command: bin/nimpretty
    plugs: [home]
  nimsuggest:
    command: bin/nimsuggest
    plugs: [home]
  testament:
    command: bin/testament
    plugs: [home]

parts:
  nim-build:
    plugin: dump
    source: https://github.com/nim-lang/Nim.git
    override-build: |
      
      case "$SNAPCRAFT_ARCH_TRIPLET" in
      "x86_64-linux-gnu")
        arch="amd64"
        ;;
      "arm-linux-gnueabihf")
        arch="armhf"
        ;;
      "aarch64-linux-gnu")
        arch="arm64"
        ;;
      "i386-linux-gnu")
        arch="i386"
        ;;
      *)
        echo "Unsupported architecture $SNAPCRAFT_ARCH_TRIPLET"
        exit 1
        ;;
      esac
      
      #build nim
      sh build_all.sh --os linux --cpu $arch

      #cleanup and set permissions
      rm bin/empty.txt
      chmod u+x bin/*

      #prepare and copy binaries to snap
      #mkdir "$SNAPCRAFT_PART_INSTALL"/bin
      cp -v bin/* "$SNAPCRAFT_PART_INSTALL"/bin

      #copy bash completion scripts into place
      mkdir -p "$SNAPCRAFT_PART_INSTALL"/usr/share/bash-completion/completions/
      cp -v tools/nim.bash-completion "$SNAPCRAFT_PART_INSTALL"/usr/share/bash-completion/completions/nim.sh
      cp -v dist/nimble/nimble.bash-completion "$SNAPCRAFT_PART_INSTALL"/usr/share/bash-completion/completions/nimble.sh
    build-packages:
      - gcc
      - git
