name: nim-lang-nightly
summary: Nim programming language, compiler, and other tools.
description: |
  Nim is a compiled, garbage-collected systems programming language with 
  a design that focuses on efficiency, expressiveness, and elegance.
version: 'nightly'
base: core18
grade: devel
confinement: strict

apps:
  nim:
    command: bin/nim
    plugs: [home]
  nimble:
    command: bin/nimble
    plugs: [home, network]
  nimcsources:
    command: bin/nim_csources
    plugs: [home]
  nimfind:
    command: bin/nimfind
    plugs: [home]
  nimgdb:
    command: bin/nim-gdb
    plugs: [home]
  nimgrep:
    command: bin/nimgrep
    plugs: [home]
  nimpretty:
    command: bin/nimpretty
    plugs: [home]
  nimsuggest:
    command: bin/nimsuggest
    plugs: [home]
  testament:
    command: bin/testament
    plugs: [home]
  gcc:
    command: usr/bin/gcc
    plugs: [home]
  clang:
    command: usr/bin/clang
    plugs: [home]

parts:
  nim-build:
    plugin: dump
    source: https://github.com/nim-lang/Nim.git
    override-build: |
      sh build_all.sh
      rm bin/empty.txt
      chmod u+x bin/*
      mkdir "$SNAPCRAFT_PART_INSTALL"/bin/
      ls -a bin/*
      mv bin/* "$SNAPCRAFT_PART_INSTALL"/bin/
      ls -a "$SNAPCRAFT_PART_INSTALL"/bin/*
      mkdir "$SNAPCRAFT_PART_INSTALL"/config/
      mv config/* "$SNAPCRAFT_PART_INSTALL"/
      mkdir "$SNAPCRAFT_PART_INSTALL"/lib/
      mv lib/* "$SNAPCRAFT_PART_INSTALL"/lib/
      mkdir "$SNAPCRAFT_PART_INSTALL"/doc/
      mv doc/* "$SNAPCRAFT_PART_INSTALL"/doc/
      mkdir "$SNAPCRAFT_PART_INSTALL"/usr/bin/
      cp /usr/bin/gcc "$SNAPCRAFT_PART_INSTALL"/usr/bin/
      cp /usr/bin/gcc "$SNAPCRAFT_PART_INSTALL"/usr/bin/
    build-packages:
      - gcc
      - git
      = clang