name: nim-lang-nightly
summary: Nim programming language, compiler, and other tools.
description: |
  Nim is a compiled, garbage-collected systems programming language with 
  a design that focuses on efficiency, expressiveness, and elegance.
version: 'nightly'
base: core18
grade: devel
confinement: strict

plugs:
  system-files:
    read: [/usr/lib]

apps:
  nim:
    command: bin/nim
    #completer: etc/bash_completion.d/nim
    plugs: [home,system-files]
  nimble:
    command: bin/nimble
    #completer: etc/bash_completion.d/nimble
    plugs: [home, network]
  nimcsources:
    command: bin/nim_csources
    plugs: [home]
  nimfind:
    command: bin/nimfind
    plugs: [home]
  nimgdb:
    command: bin/nim-gdb
    plugs: [home]
  nimgrep:
    command: bin/nimgrep
    plugs: [home]
  nimpretty:
    command: bin/nimpretty
    plugs: [home]
  nimsuggest:
    command: bin/nimsuggest
    plugs: [home]
  testament:
    command: bin/testament
    plugs: [home]
  gcc:
    command: usr/bin/gcc
    plugs: [home]

#layout:
#  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET:
#    bind: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET

#layout:
#  /usr/lib/gcc/$SNAPCRAFT_ARCH_TRIPLET:
#    bind: $SNAP/usr/lib/gcc/$SNAPCRAFT_ARCH_TRIPLET

parts:
  nim-build:
    plugin: dump
    source: https://github.com/nim-lang/Nim.git
    override-build: |
      
      case "$SNAPCRAFT_ARCH_TRIPLET" in
      "x86_64-linux-gnu")
        arch="amd64"
        ;;
      "arm-linux-gnueabihf")
        arch="armhf"
        ;;
      "aarch64-linux-gnu")
        arch="arm64"
        ;;
      "i386-linux-gnu")
        arch="i386"
        ;;
      *)
        echo "Unsupported architecture $SNAPCRAFT_ARCH_TRIPLET"
        exit 1
        ;;
      esac
      
      sh build_all.sh --os linux --cpu $arch
      rm bin/empty.txt
      chmod u+x bin/*
      mkdir "$SNAPCRAFT_PART_INSTALL"/bin
      mv bin/* "$SNAPCRAFT_PART_INSTALL"/bin
      mv lib/* "$SNAPCRAFT_PART_INSTALL"/lib
      #"$SNAPCRAFT_PART_INSTALL"/bin/nimble refresh
      #mkdir -p "$SNAPCRAFT_PART_INSTALL"/etc/bash_completion.d
      #mv tools/nim.bash-completion "$SNAPCRAFT_PART_INSTALL"/etc/bash_completion.d/nim
      #mv dist/nimble/nimble.bash-completion "$SNAPCRAFT_PART_INSTALL"/etc/bash_completion.d/nimble
    stage-packages:
      - gcc
      - libgcc-5-dev
      - libgcc1
      - libc6-dev
      - linux-libc-dev
    build-packages:
      - gcc
      - git
    #prime:
      #- -share/man
      #- -share/doc
      #- -usr/share/doc
      #- -usr/share/lintian
      #- -usr/share/man
      #- -usr/share/bug