name: nim-lang-nightly
summary: Nim programming language, compiler, and other tools.
description: |
  Nim is a compiled, garbage-collected systems programming language with 
  a design that focuses on efficiency, expressiveness, and elegance.
version: 'nightly'
base: core18
grade: devel
confinement: strict

apps:
  nim:
    command: bin/nim
  nimble:
    command: bin/nimble
  nimcsources:
    command: bin/nim_csources
  nimfind:
    command: bin/nimfind
  nimgdb:
    command: bin/nim-gdb
  nimgrep:
    command: bin/nimgrep
  nimpretty:
    command: bin/nimpretty
  nimsuggest:
    command: bin/nimsuggest
  testament:
    command: bin/testament

parts:
  nim-build:
    plugin: dump
    source: https://github.com/nim-lang/Nim.git
    override-build: |
      sh build_all.sh
      rm bin/empty.txt
      chmod u+x bin/*
      mkdir "$SNAPCRAFT_PART_INSTALL"/bin/
      ls -a bin/*
      mv bin/* "$SNAPCRAFT_PART_INSTALL"/bin/
      ls -a "$SNAPCRAFT_PART_INSTALL"/bin/*
      mkdir "$SNAPCRAFT_PART_INSTALL"/config/
      mv config/* "$SNAPCRAFT_PART_INSTALL"/
      mkdir "$SNAPCRAFT_PART_INSTALL"/lib/
      mv lib/* "$SNAPCRAFT_PART_INSTALL"/lib/
      mkdir "$SNAPCRAFT_PART_INSTALL"/doc/
      mv doc/* "$SNAPCRAFT_PART_INSTALL"/doc/
    build-packages:
      - gcc
      - git