name: nim-lang-lts-1
summary: Nim programming language, compiler, and other tools.
description: |
  Nim is a compiled, garbage-collected systems programming language with 
  a design that focuses on efficiency, expressiveness, and elegance.
version: VERSION
base: core18
grade: stable
confinement: strict

apps:
  nim:
    command: bin/nim
    completer: bin/nim.bash-completion
    plugs: [home]
  nimble:
    command: bin/nimble
    completer: bin/nimble.bash-completion
    plugs: [home, network]
  nimcsources:
    command: bin/nim_csources
    plugs: [home]
  nimfind:
    command: bin/nimfind
    plugs: [home]
  nimgdb:
    command: bin/nim-gdb
    plugs: [home]
  nimgrep:
    command: bin/nimgrep
    plugs: [home]
  nimpretty:
    command: bin/nimpretty
    plugs: [home]
  nimsuggest:
    command: bin/nimsuggest
    plugs: [home]
  testament:
    command: bin/testament
    plugs: [home]

parts:
  nim-build:
    source: RELEASEURL
    source-type: tar
    plugin: autotools
    override-build: |
      sh build_all.sh --os linux --cpu amd64
      bin/nim c koch
      ./koch tools
      rm bin/empty.txt
      chmod u+x bin/*
      mv bin/* "$SNAPCRAFT_PART_INSTALL"/bin
      mv lib/* "$SNAPCRAFT_PART_INSTALL"/lib
      mkdir -p "$SNAPCRAFT_PART_INSTALL"/etc/bash_completion.d
      mv tools/nim.bash-completion "$SNAPCRAFT_PART_INSTALL"/etc/bash_completion.d/nim
      mv dist/nimble/nimble.bash-completion "$SNAPCRAFT_PART_INSTALL"/etc/bash_completion.d/nimble
    stage-packages:
      - gcc
      - libgcc-5-dev
    build-packages:
      - gcc
      - git