name: nim-lang
summary: Nim programming language, compiler, and other tools.
description: |
  Nim is a compiled, garbage-collected systems programming language with 
  a design that focuses on efficiency, expressiveness, and elegance.
version: VERSION
base: core18
grade: stable
confinement: strict

apps:
  nim:
    command: /bin/nim
  nimble:
    command: /bin/nimble
  nimcsources:
    command: /bin/nim_csources
  nimfind:
    command: /bin/nimfind
  nimgdb:
    command: /bin/nim-gdb
  nimgrep:
    command: /bin/nimgrep
  nimpretty:
    command: /bin/nimpretty
  nimsuggest:
    command: /bin/nimsuggest
  testament:
    command: /bin/testament

parts:
  nim-build:
    source: RELEASEURL
    source-type: tar
    plugin: autotools
    override-build: |
      sh build_all.sh
      bin/nim c koch
      ./koch tools
      rm bin/empty.txt
      chmod u+x bin/*
      mkdir "$SNAPCRAFT_PART_INSTALL"/bin/
      mv bin/* "$SNAPCRAFT_PART_INSTALL"/bin/
      mkdir "$SNAPCRAFT_PART_INSTALL"/config/
      mv config/* "$SNAPCRAFT_PART_INSTALL"/
      mkdir "$SNAPCRAFT_PART_INSTALL"/lib/
      mv lib/* "$SNAPCRAFT_PART_INSTALL"/lib/
      mkdir "$SNAPCRAFT_PART_INSTALL"/doc/
      mv doc/* "$SNAPCRAFT_PART_INSTALL"/doc/
    build-packages:
      - gcc
      - git
