name: docs
on:
  push:
    branches:
    - master
  schedule:
   - cron: 0 22 * * *
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: sirredbeard/snap-build
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: |
        sudo apt-get update
        cd docs
        snapcraft
    - name: Push snap to Snap Store
      env:
        SNAPCRAFT_LOGIN_FILE: ${{ secrets.SNAPCRAFT_LOGIN_FILE }}
      run: |
        cd docs
        mkdir .snapcraft
        echo ${SNAPCRAFT_LOGIN_FILE} | base64 --decode --ignore-garbage > .snapcraft/snapcraft.cfg
        snapcraft push --release=stable *.snap
