name: edge
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: snapcore/snapcraft
    steps:
    - uses: actions/checkout@v1
    - name: Prepare
      run: |
        snap refresh
        snap install core18
    - name: Build
      run: |
        cd edge
        snapcraft
