name: nightly
on:
  push:
    branches:
    - master
  schedule:
   - cron: 0 22 * * *
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: snapcore/snapcraft
    steps:
    - uses: actions/checkout@v1
    - name: Build
      env:
        SNAPCRAFT_LOGIN_FILE: ${{ secrets.REMOTE_BUILD_CREDENTIALS }}
      run: |
        sudo apt-get update
        sudo apt-get remove snapcraft -y
        sudo apt-get install snapd -y
        snap install snapcraft
        mkdir -p $HOME/.local/share/snapcraft/provider/launchpad/
        echo ${SNAPCRAFT_LOGIN_FILE} | base64 --decode --ignore-garbage > $HOME/.local/share/snapcraft/provider/launchpad/credentials
        cd nightly
        snapcraft remote-build --launchpad-accept-public-upload
    - name: Push snap
      env:
        SNAPCRAFT_LOGIN_FILE: ${{ secrets.SNAPCRAFT_LOGIN_FILE }}
      run: |
        cd nightly
        mkdir .snapcraft
        echo ${SNAPCRAFT_LOGIN_FILE} | base64 --decode --ignore-garbage > .snapcraft/snapcraft.cfg
        snapcraft push --release=edge *.snap
