name: nightly
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: snapcore/snapcraft
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: |
        cd nightly
        snapcraft
#    - uses: actions/upload-artifact@master
#      with:
#        name: snap
#        path: *.snap
#
#  push:
#    runs-on: ubuntu-latest
#    container:
#      image: snapcore/snapcraft
#    steps:
#      - uses: actions/download-artifact@master
#        with:
#          name: snap
#      - run: |
#         ls *.snap
#         snapcraft push --release=devel *.snap
