name: nightly
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: snapcore/snapcraft
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: |
        cd nightly
        snapcraft
    - name: Push snap
      env:
        SNAPCRAFT_LOGIN_FILE: ${{ secrets.SNAPCRAFT_LOGIN_FILE }}
      run: |
        mkdir .snapcraft
        echo ${SNAPCRAFT_LOGIN_FILE} | base64 --decode --ignore-garbage > .snapcraft/snapcraft.cfg
        snapcraft push --release=edge *.snap
