name: nightly
on:
  push:
    branches:
    - master
  schedule:
   - cron: 0 22 * * *
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: sirredbeard/bionic-snap-build
    steps:
    - uses: actions/checkout@v1
    - name: Build
      env:
        REMOTE_BUILD_CREDENTIALS: ${{ secrets.REMOTE_BUILD_CREDENTIALS }}
      run: |
        
        #temporary
        git config --global user.email "you@example.com"
        git config --global user.name "Your Name"
        
        mkdir -p $HOME/.local/share/snapcraft/provider/launchpad/
        echo ${REMOTE_BUILD_CREDENTIALS} | base64 --decode --ignore-garbage > $HOME/.local/share/snapcraft/provider/launchpad/credentials
        cd nightly
        snapcraft remote-build --launchpad-accept-public-upload
    - name: Push snap
      env:
        SNAPCRAFT_LOGIN_FILE: ${{ secrets.SNAPCRAFT_LOGIN_FILE }}
      run: |
        cd nightly
        mkdir .snapcraft
        echo ${SNAPCRAFT_LOGIN_FILE} | base64 --decode --ignore-garbage > .snapcraft/snapcraft.cfg
        snapcraft push --release=edge *.snap
