name: stable
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: snapcore/snapcraft
    steps:
    - uses: actions/checkout@v1
    - name: Configure template
      run: |
        apt-get install python3-pip python3-setuptools python3-wheel -y
        useradd -m temp
        chown -R temp /home/temp
        su temp -c "pip3 install lastversion"
        VERSION=$(su temp -c "~/.local/bin/lastversion nim-lang/Nim")
        RELEASEURL=$(su temp -c "~/.local/bin/lastversion --assets nim-lang/Nim")
        sed -i "s/VERSION/$VERSION/g" "stable/snap/snapcraft.yaml"
        sed -i "s*RELEASEURL*$RELEASEURL*g" "stable/snap/snapcraft.yaml"
    - name: Build snap
      run: |
        cd stable
        snapcraft
        mv nim-lang_*_amd64.snap nim-lang_amd64.snap
    - uses: actions/upload-artifact@master
      with:
        name: snap
        path: nim-lang_amd64.snap

  push:
    runs-on: ubuntu-latest
    container:
      image: snapcore/snapcraft
    steps:
      - uses: actions/download-artifact@master
        with:
          name: snap
      - name: Push snap
        env:
          SNAPCRAFT_LOGIN_FILE: ${{ secrets.SNAPCRAFT_LOGIN_FILE }}
        run: |
         ls -a
         mkdir .snapcraft
         echo $SNAPCRAFT_LOGIN_FILE | base64 --decode --ignore-garbage > .snapcraft/snapcraft.cfg
         snapcraft push --release=stable *.snap
