name: stable
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: snapcore/snapcraft
    steps:
    - uses: actions/checkout@v1
    - name: Configure
      run: |
        apt-get install python3-pip -y
        pip3 install lastversion
        # get latest release info
    - name: Build
      run: |
        cd stable
        #snapcraft
